### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by siterui** [camalot/madb#13]
code:
AdbHelper.Instance.GetDevices(AndroidDebugBridge.SocketAddress).First().Screenshot.ToImage().Save("d:\\1.png");

image:
http://ww3.sinaimg.cn/mw690/6aa5f210gw1f2yzmqei3rj20k00zkn6p.jpg

Normal screenshot：
http://ww1.sinaimg.cn/mw690/6aa5f210gw1f2yzmqxqt4j20k00zk76w.jpg

**Comment by camalot** [comment]
can you provide information on the device? 

I know what the problem is here, but I want to see what the device expects the image format to be.

**Comment by siterui** [comment]
Is this the right one?
http://ww4.sinaimg.cn/mw690/6aa5f210gw1f2zlr7l1p0j20k01zkaej.jpg

**Comment by camalot** [comment]
that helps, thanks.

**Comment by siterui** [comment]
You are welcome. Thank you for your open source.
