### ISSUE TITLE
Working with Visual Studio 2015 & .net 4.5.2

### ISSUE THREAD

**Issue by GermMuz** [camalot/madb#15]
The morelinq dependency does not load in a new WPF project created with Visual Studio 2015, .net 4.5.2, is there a work around for this?

Thank you

**Comment by camalot** [comment]
What version of the nuget package are you using? can you try one of the -Pre (-beta) releases if you are not already.

**Comment by camalot** [comment]
no response, unable to reproduce. I am closing this. please reopen if you have an issue with the latest builds.
