### ISSUE TITLE
Can the screen be synchronized to PC

### ISSUE THREAD

**Issue by siterui** [camalot/madb#16]
Can the screen be synchronized to PC?
similar：Android Screen Monitor

**Comment by camalot** [comment]
Not in the current code base. I have not found a way to do it efficiently yet. the FPS is like 3 - 5 and that is WAY too slow.

**Comment by siterui** [comment]
Thank you

This software can be done, but not open source, you can see, maybe get some inspiration

http://tc.sigma-rt.com/index.php
