### ISSUE TITLE
Suffix upper case lead to upload failed

### ISSUE THREAD

**Issue by siterui** [camalot/madb#17]
var pushPaths = new string[] {@“c:\123.JPG” };
SyncResult rust =drivce.SyncService.Push(pushPaths, remote, new NullSyncProgressMonitor());

rust.Code=0
But the phone can not find the file
123.JPG Modify as: 123.jpg success

**Comment by camalot** [comment]
how are you attempting to 'find the file'?

you have to find the file as `123.JPG`.
or, if that is what you are looking for, than there may be a bug where extensions are lower-cased.
