### ISSUE TITLE
Error with GetDevices

### ISSUE THREAD

**Issue by grantmakesplane** [camalot/madb#41]
Get an error with GetDevices()

var device = AdbClient.Instance.GetDevices().First();

An unhandled exception of type 'System.ArgumentException' occurred in SharpAdbClient.dll

Additional information: Invalid device list data '01f15dd79990d792       device product:g2_vzw model:VS980_4G device:g2 transport_id:3'

A bug?

**Comment by camalot** [comment]
SharpAdbClient is not this project. that is the fork by quamotion.

It does look like a bug in their code though, looks like they are not expecting the `transport_id` data
