### ISSUE TITLE
Library doesn't start adb server, depends on one running already

### ISSUE THREAD

**Issue by gamesguru** [camalot/madb#44]
suitable method is empty, _AndroidDebugBridge.cs_
`
private static void StartServer( ) {
}`

need to add 'adb start-server' command to the method

**Comment by camalot** [comment]
Does this refer to `StartServer` in the `MadBee.Console`? That is just a sample application. it has nothing to do with `AndroidDebugBridge` directly. 

`AndroidDebugBridge` has `Start`, which is called automatically when you call `AndroidDebugBridge.CreateBridge`

**Comment by gamesguru** [comment]
I am not sure this is done then in the most intuitive way, or that it is documented properly in the readme because I am having issues and so are all of my colleagues with always having to `adb start-server` manually out of the command prompt to have any devices detected at all by your framework.  Clearly we are missing something.

Windows10, adb v1.0.39
